"""empty message

Revision ID: 31caf810c7e6
Revises: ee04d4872708
Create Date: 2019-10-14 13:24:30.607374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31caf810c7e6'
down_revision = 'ee04d4872708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userchoice',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('top_choice', sa.Integer(), nullable=True),
    sa.Column('bottom_choice', sa.Integer(), nullable=True),
    sa.Column('footwear_choice', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userchoice')
    # ### end Alembic commands ###
