"""empty message

Revision ID: 78cf77779523
Revises: 31caf810c7e6
Create Date: 2019-10-15 04:32:36.603864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cf77779523'
down_revision = '31caf810c7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables')
    # ### end Alembic commands ###
